### ISSUE TITLE
Several findings in package version and liscense file missing in the code.

### ISSUE THREAD

**Issue by zhunangua** [Cavendish518/SFPNet#4]
Hi, I tried to modify your demo.py file and run the checkpoint for KITTI . Then I found that it would report an error about shape on 4090. This may be because the minimum version of spconv library supported by 4090 handles input and output channels differently, e.g. [5,5,5,256,256] and [256,5,5,5,256]. Adjust the order and it will work.

**Comment by zhunangua** [comment]
The license file is only provided in S.MID. Could you please add a license file for code? Thanks!

**Comment by Cavendish518** [comment]
> Hi, I tried to modify your demo.py file and run the checkpoint for KITTI . Then I found that it would report an error about shape on 4090. This may be because the minimum version of spconv library supported by 4090 handles input and output channels differently, e.g. [5,5,5,256,256] and [256,5,5,5,256]. Adjust the order and it will work.

Many thanks for sharing the information.

**Comment by Cavendish518** [comment]
> The license file is only provided in S.MID. Could you please add a license file for code? Thanks!

LICENSE file has been added.
